import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from "react"
import { useQuill } from "react-quilljs"
import { Button, useToast } from '@chakra-ui/react'
import { sample } from '../sample/ap-suat-lop'

export default function Home() {
  const { quill, quillRef } = useQuill()
  const toast = useToast()
  console.log("!");
  useEffect(() => {
    if (quill) {
      let html = sample
      html = html.replace(`<font face="Arial, Helvetica, sans-serif">`, '<span>')
      html = html.replace(`<font color="#e74c3c">`, '<span style="color:#e74c3c">')
      html = html.replace('</font>', '</span>')
      html = html.replace('div', 'span')
      console.log(html)
      quill.root.innerHTML = html
    }
  }, [quill])
  const replaceClasses = [
    {
      quill: 'class="ql-align-center',
      css: 'style="text-align: center;"',
    },
    {
      quill: 'class="ql-align-justify"',
      css: 'style="text-align: justify;"',
    },
    {
      quill: 'class="ql-size-large"',
      css: 'style="font-size: 16px;"',
    },
    {
      quill: '',
      css: '',
    },
    {
      quill: '',
      css: '',
    },
    {
      quill: '',
      css: '',
    },
  ]
  function copyHtml() {
    let html = quill.root.innerHTML
    replaceClasses.forEach(item => {
      html = html.replaceAll(item.quill, item.css)
    })
    navigator.clipboard.writeText(html)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>SEO HTML</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button margin={1} size='xs' onClick={() => {
          copyHtml()
          toast({
            title: 'HTML copied.',
            status: 'success',
            duration: 1000,
            isClosable: true,
          })
        }}
        >Copy HTML</Button>
        <div>
          <div className={styles.quill} ref={quillRef} />
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by{' '}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </footer>
    </div>
  )
}
